add_newline = false

# this is a multi-line prompt; I experimented with it but never liked it enough to want to keep it
format = '''
[â•­â”€â”€â”€â”€](fg:#6272a4)[â—–](blue)$cmd_duration$status$jobs[â–®](blue)$username$hostname
[â•°](fg:#6272a4)[â–®](blue)$directory$shlvl$character[â——](blue) '''

#format = "[â—–](blue)$status$jobs$cmd_duration$username$hostname[â–®](blue)$directory$shlvl$character[â——](blue) "
#right_format = """[(â—–$git_status$git_branch)](blue)$git_commit"""


[character]
format = "$symbol"
success_symbol = "[â–®](green)"
error_symbol = "[â–®](red)"
vicmd_symbol = "[â–¯](fg:#ff79c6)"  # orange

[username]  # only shows if we are in ssh
style_user = "fg:#ff79c6"
style_root = "red"
format = "[â–®](blue)[$user]($style)"
show_always = false

[hostname]
ssh_only = true
trim_at = "."
style = "fg:#ff79c6"
format = "[@](blue)[$hostname]($style)"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "yellow"
read_only = " ğŸ”’"
read_only_style = "fg:#ffb86c"
truncation_symbol = "â‹¯"
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style)"

[status]
style = "red"
symbol = "â—©"
signal_symbol = "â†¯"
not_found_symbol = "âˆ…"
not_executable_symbol = "â‡"
sigint_symbol = "â¤“"
success_symbol = "[â—¼](green)"
map_symbol = true
format = "[$symbol$maybe_int]($style)"
disabled = false

[jobs]
symbol_threshold = 1
number_threshold = 2
symbol = "[âŠ™](fg:#ffb86c)"
style = "fg:ffb86c"
format = """[â–®](blue)$symbol[$number]($style)"""

[cmd_duration]
min_time = 5_000
show_milliseconds = false
style = "bold yellow"
min_time_to_notify = 60_000
show_notifications = false
format = "[â–®](blue)[âŸ¦Î´t:](fg:#6272a4) [$duration]($style)[âŸ§](fg:#6272a4)"

[shlvl]
threshold = 2
symbol = "[â†•](fg:#ff79c6)"
style = "bold fg:#ff79c6"
format = "[$symbol$shlvl]($style)"
disabled = false

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
modified = "[â—¨](fg:#ffb86c)"
staged = '[+\($count\)](yellow)'
untracked = "â–¨"
up_to_date = "[âœ“](green)"
style = "fg:#ffb86c"
format = "[$all_status]($style)"

[git_branch]
symbol = "î‚ "
truncation_length = 12
truncation_symbol = "â‹¯"
only_attached = false
style = "purple"
format = "[â–®](blue)[$symbol$branch]($style)"

[git_commit]
commit_hash_length = 6
tag_symbol = "â¢"
only_detached = false
format = "[â–®](blue)[$hash$tag](cyan)"
